export interface GlobeRuntimeSettings {
  zoomThreshold: number;
  autoRotate: boolean;
  autoRotateSpeed: number;
  dragRotateSpeed: number;
  useInertia: boolean;
  inertiaDamping: number;
  wireStrength: number;
  hatchStrength: number;
  crosshatchDensity: number;
  crosshatchThreshold: number;
  showAtmosphere: boolean;
  atmosphereColor: string;
  atmosphereAltitude: number;
  pointRadius: number;
  pointAltitude: number;
  markerScale: number;
  boundaryOpacity: number;
  showInternationalBorders: boolean;
  internationalBorderThickness: number;
  showAdmin1Divisions: boolean;
  admin1Thickness: number;
  admin1DashLength: number;
  admin1DashGap: number;
  showAdmin2Divisions: boolean;
  admin2DotSize: number;
  admin2DotGap: number;
  showCurvedTitle: boolean;
  enablePaperEffect: boolean;
  paperGrainStrength: number;
  paperHalftoneStrength: number;
  paperInkStrength: number;
}

export const DEFAULT_GLOBE_RUNTIME_SETTINGS: GlobeRuntimeSettings = {
  zoomThreshold: 1.8,
  autoRotate: true,
  autoRotateSpeed: 0.05,
  dragRotateSpeed: 1.1,
  useInertia: false,
  inertiaDamping: 0.22,
  wireStrength: 1,
  hatchStrength: 1,
  crosshatchDensity: 1,
  crosshatchThreshold: 0.8,
  showAtmosphere: true,
  atmosphereColor: "#4f72ff",
  atmosphereAltitude: 0.13,
  pointRadius: 0.4,
  pointAltitude: 0.01,
  markerScale: 1,
  boundaryOpacity: 1,
  showInternationalBorders: true,
  internationalBorderThickness: 0.98,
  showAdmin1Divisions: true,
  admin1Thickness: 0.64,
  admin1DashLength: 0.35,
  admin1DashGap: 0.35,
  showAdmin2Divisions: true,
  admin2DotSize: 0.1,
  admin2DotGap: 0.22,
  showCurvedTitle: true,
  enablePaperEffect: false,
  paperGrainStrength: 0.75,
  paperHalftoneStrength: 0.8,
  paperInkStrength: 0.9,
};
