insert into public.events (
  id,
  name,
  date,
  manual_location,
  address,
  lat,
  lng,
  description,
  is_lexer_coming,
  recurrent,
  invite_url,
  cost,
  currency,
  has_additional_tiers
)
values
  (
    'office-hours-sf-2026-02-10',
    'Office Hours SF',
    '2026-02-11T02:30:00Z',
    'Bay Area, CA',
    'Zeitgeist, 199 Valencia St, San Francisco, CA 94103',
    37.7701,
    -122.4222,
    'Weekly Tuesday hang at Zeitgeist, 6:30-10:00 PM. Media/builders crowd and good collisions.',
    false,
    true,
    'https://x.com/OfficeHoursGlobal',
    0,
    'USD',
    false
  ),
  (
    'vibecamp-5-2026',
    'Vibecamp 5',
    '2026-06-18T16:00:00Z',
    'Bay Area, CA',
    'Berkeley, CA (final venue details on host page)',
    37.8715,
    -122.273,
    'Vibecamp 5 (June 18-21, 2026). Theme: Fivecamp. Internet-friends IRL festival energy.',
    false,
    false,
    'https://my.vibe.camp',
    0,
    'USD',
    true
  ),
  (
    'manifest-2026-placeholder',
    'Manifest',
    '2026-06-05T17:00:00Z',
    'Bay Area, CA',
    'Lighthaven, 2740 Telegraph Ave, Berkeley, CA 94705',
    37.8592,
    -122.2591,
    'Prediction markets / futures / ideas festival at Lighthaven. Confirm exact 2026 dates on manifest.is.',
    false,
    false,
    'https://manifest.is/',
    0,
    'USD',
    true
  ),
  (
    'inkhaven-2026-cohort-2',
    'Inkhaven Residency (Cohort 2)',
    '2026-04-01T16:00:00Z',
    'Bay Area, CA',
    'Lighthaven, 2740 Telegraph Ave, Berkeley, CA 94705',
    37.8592,
    -122.2591,
    '30-day writing residency in Berkeley (April 1-30, 2026). Publish daily or pack your bags.',
    false,
    false,
    'https://www.inkhaven.blog/',
    3500,
    'USD',
    true
  )
on conflict (id) do update set
  name = excluded.name,
  date = excluded.date,
  manual_location = excluded.manual_location,
  address = excluded.address,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  is_lexer_coming = excluded.is_lexer_coming,
  recurrent = excluded.recurrent,
  invite_url = excluded.invite_url,
  cost = excluded.cost,
  currency = excluded.currency,
  has_additional_tiers = excluded.has_additional_tiers,
  updated_at = now();
